name: E2E Tests

concurrency:
  group: one-at-time
  cancel-in-progress: false

on: [workflow_dispatch]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Run tests
        run: make test-e2e
        env:
          AUTHOK_DOMAIN: ${{ secrets.AUTHOK_DOMAIN }}
          AUTHOK_CLIENT_ID: ${{ secrets.AUTHOK_CLIENT_ID }}
          AUTHOK_CLIENT_SECRET: ${{ secrets.AUTHOK_CLIENT_SECRET }}

      - name: Update codecov report
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.out
          fail_ci_if_error: false
          verbose: true
